version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: db_${PROJECT_NAME}
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
     - db
    image: wordpress:latest
    container_name: wp_${PROJECT_NAME}
    ports:
      - "8000:80"
    volumes:
      - ../www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini

    environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: ${MYSQL_USER}
     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_${PROJECT_NAME}
    depends_on:
      - db
    ports:
      - "8100:80"